[package]
name = "secret"
version = "0.1.0"
edition = "2018"

[lib]
name = "secret"
path = "src/lib.rs"

[[bin]]
name = "secret"
path = "src/main.rs"

[dependencies]
regex = "1.5"
rand = "0.8.0"
clap = "2.33.3"
